[mongodb]
172.31.38.234


[ansible2]
54.242.62.61
54.242.62.61

[catalogue]

[local]
localhost

[local:vars]
COURSE=Ansible
DURATION=15hrs
TRAINER=Ashokkumar

[all.vars]
ansible_user=ec2-user
ansible_password=DevOps321
